### ISSUE TITLE
When using view inside ViewGroup hierarchy margin inside view is not enough

### ISSUE THREAD

**Issue by mhrjnamar** [fornewid/neumorphism#1]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#212121"
    android:clipChildren="false"
    android:orientation="vertical"
    tools:context=".activities.SearchActivity">

    <EditText
        android:id="@+id/searchBar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginStart="16dp"
        android:layout_marginEnd="16dp"
        android:autofillHints=""
        android:drawableEnd="@android:drawable/ic_menu_search"
        android:hint="@string/search"
        android:inputType="textShortMessage"
        android:theme="@style/ThemeOverlay.AppCompat.Dark"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

    <soup.neumorphism.NeumorphCardView
        android:id="@+id/searchBySong"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_margin="8dp"
        android:layout_marginStart="16dp"
        android:layout_marginEnd="16dp"
        android:background="?selectableItemBackground"
        android:clickable="true"
        android:focusable="true"
        android:paddingStart="16dp"
        android:paddingTop="12dp"
        android:paddingEnd="16dp"
        android:paddingBottom="12dp"
        app:layout_constraintEnd_toStartOf="@+id/searchByPoster"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/searchBar">

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:drawableTint="@color/yellowTextColor"
            android:text="Option1"
            android:gravity="center"
            android:textAppearance="?android:attr/textAppearanceSmall"
            android:textColor="@color/yellowTextColor" />
    </soup.neumorphism.NeumorphCardView>

    <soup.neumorphism.NeumorphCardView
        android:id="@+id/searchByPoster"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginStart="16dp"
        android:layout_marginTop="8dp"
        android:layout_marginEnd="16dp"
        android:background="?selectableItemBackground"
        android:clickable="true"
        android:focusable="true"
        android:paddingStart="16dp"
        android:paddingTop="12dp"
        android:paddingEnd="16dp"
        android:paddingBottom="12dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toEndOf="@+id/searchBySong"
        app:layout_constraintTop_toBottomOf="@+id/searchBar">

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:drawableTint="@color/redTextColor"
            android:text="Option2"
            android:gravity="center"
            android:textAppearance="?android:attr/textAppearanceSmall"
            android:textColor="@color/redTextColor" />
    </soup.neumorphism.NeumorphCardView>

    </LinearLayout>

</LinearLayout>

![viber_image_2020-04-04_01-12-02](https://user-images.githubusercontent.com/17248241/78397862-b9167600-7611-11ea-8e87-5d8dd3deda0a.jpg)

**Comment by fornewid** [comment]
Thanks for reporting!

Currently shadows are drawn outside the view's area.
So if you want to fix this in current version,
please add `android:clipChildren="false"` attribute at your `LinearLayout`.

```diff
 <LinearLayout
     android:layout_width="match_parent"
     android:layout_height="match_parent"
+    android:clipChildren="false"
     >
     <soup.neumorphism.NeumorphCardView />
     <soup.neumorphism.NeumorphCardView />
 </LinearLayout>
```

Yep, this behavior does not look very good.
So I'm going to work to draw a shadow inside the view area as soon as possible.

**Comment by fornewid** [comment]
In `0.1.8` version, this issue is fixed.
You may be wondering how it was modified.

Instead of `android:clipChildren="false"`, supports padding for NeumorphShapeDrawable.

![neumorphism](https://user-images.githubusercontent.com/3405740/82107748-06cfe380-9765-11ea-8f1a-d2dac789adcf.jpeg)

In default, `12dp` padding is set.
And the padding can be customized by you. (`android:padding="20dp"`)
However, please use more than this default value.
