### ISSUE TITLE
radiogroup

### ISSUE THREAD

**Issue by Rabbitg** [fornewid/neumorphism#10]
개인적인 희망이지만 라디오 그룹 버튼도 있었으면 합니다 ㅠㅠ

안드로이드 스튜디오 초보이지만 레이아웃에 추가하면 안드로이드 스튜디오에서
예를들어 NeumorphImageButton 를 추가하면 오른쪽에 디자인이 보여지지 않고 가상머신에서
매일 확인하게 되네요..

**Comment by fornewid** [comment]
RadioGroup도 아래처럼 CardView로 감싸는 형태로 사용할 수 있습니다. :)

```
<soup.neumorphism.NeumorphCardView
    style="@style/Widget.Neumorph.CardView"
    ...>

    <RadioGroup>
        <RadioButton />
        <RadioButton />
    </RadioGroup>
</soup.neumorphism.NeumorphCardView>
```

AndroidStudio에서 Layout Preview가 보이지 않는 것은 버그입니다.
이건 별도로 수정하겠습니다.

**Comment by Rabbitg** [comment]
> RadioGroup도 아래처럼 CardView로 감싸는 형태로 사용할 수 있습니다. :)
> 
> ```
> <soup.neumorphism.NeumorphCardView
>     style="@style/Widget.Neumorph.CardView"
>     ...>
> 
>     <RadioGroup>
>         <RadioButton />
>         <RadioButton />
>     </RadioGroup>
> </soup.neumorphism.NeumorphCardView>
> ```
> 
> AndroidStudio에서 Layout Preview가 보이지 않는 것은 버그입니다.
> 이건 별도로 수정하겠습니다. (#11)

답변해주셔서 감사합니다 ^^ !!

**Comment by Raj-spbi** [comment]
ERROR: Failed to resolve: com.github.fornewid:neumorphism:0.1.10
Show in Project Structure dialog
Affected Modules: app
What to do?? Help me please
