### ISSUE TITLE
Failed to find '@attr/colorShadowDark' in current theme. Design preview not showing

### ISSUE THREAD

**Issue by dhananjayvtro** [fornewid/neumorphism#111]
Failed to find '@attr/colorShadowDark' in current theme.

Render error 

In Android Studio Dolphin | 2021.3.1

**Comment by Vibek-exe** [comment]
have you get any resolution for this, i am also getting same issue.

**Comment by dhananjayvtro** [comment]
Not yet I am waiting for answer

**Comment by Vibek-exe** [comment]
i get the solution of this

**Comment by Vibek-exe** [comment]
![1664915478515670328477131699967](https://user-images.githubusercontent.com/78261707/193920849-98428b70-c4dc-4bfc-85e6-e09f3b5ccc60.jpg)
Just define these 2 colour in your colour resources file.

**Comment by dhananjayvtro** [comment]
Very Thanks Its resolved.
