### ISSUE TITLE
There is a NPE when I am trying to navigate to another fragment via current neum.Button 

### ISSUE THREAD

**Issue by Dorokhovyegor** [fornewid/neumorphism#14]
![image](https://user-images.githubusercontent.com/37757367/82566067-0e87f180-9b84-11ea-88c8-47c8c2139230.png)

**Comment by fornewid** [comment]
This bug should be fixed in `0.1.10` version.
I can reproduce it too, but it is not the same as the stacktrace above.
Please check this issue is also fixed on your usecases.
If not, please tell me how to reproduce it in detail.

**Comment by fornewid** [comment]
Close this. If you have another issue, please re-open.
