### ISSUE TITLE
Set gradient background to NeumorphCardView

### ISSUE THREAD

**Issue by rashmitank27** [fornewid/neumorphism#16]
I am not able to set gradient background to NeumorphCardView. Please give me example on how to do it.

**Comment by fornewid** [comment]
This library uses `android:background` to draw neumorphism decoration.
So you can't use `android:background` attributes for Neumoprh widgets. (Not working)

Instead you can get it by adding a view that draws the background.
See the following code:
```xml
<soup.neumorphism.NeumorphCardView>
    <View
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@drawable/gradation" />
</soup.neumorphism.NeumorphCardView>
```

**Comment by fornewid** [comment]
If it still reproduces, please reopen.

**Comment by fluttyCat** [comment]
i can not add gradiant background to neu button too. what should i do?
