### ISSUE TITLE
I'm getting Failed to Resolve Error !

### ISSUE THREAD

**Issue by Raj-spbi** [fornewid/neumorphism#17]
Version used:
Devices/Android versions reproduced on:

I would appreciate if you could attach:
- Sample codes to trigger the issue.
- A screenrecord or screenshots showing the issue.
Failed to resolve: com.github.fornewid:neumorphism:0.1.10

**Comment by fornewid** [comment]
Did you add jitpack maven? 🤔 
```groovy
allprojects {
    repositories {
        maven { url "https://jitpack.io" }
    }
}
```
And the latest version is `0.1.11`.

**Comment by fornewid** [comment]
After the upper codes and it still reproduces, please reopen.

**Comment by Raj-spbi** [comment]
Thankyou so much sir.It's working 😊

**Comment by singhbabu9455** [comment]
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.fornewid:neumorphism:{latest_version}.
   facing this problem
