### ISSUE TITLE
카드뷰와 버튼을 같이 쓰고 싶은데 어떻게 해야할지..

### ISSUE THREAD

**Issue by Rabbitg** [fornewid/neumorphism#18]
![image](https://user-images.githubusercontent.com/51067267/83750761-baf7c680-a6a0-11ea-8c12-d838b8a50061.png)
위 사진과 같이 하고싶은데 라이브러리로 하면 제가 하고자하는 방향대로 잘안되네요,,

![image](https://user-images.githubusercontent.com/51067267/83750818-d4990e00-a6a0-11ea-8e61-c69c822090be.png)
위 사진 처럼 버튼이 뜬다(?)라고 표현을 해야하는 건지,, 혹시 이러한 문제를 아신다면 해결방법좀 알려주실 수 있을까요??
구체적이지 못한 질문 죄송합니다..

**Comment by fornewid** [comment]
일반적으로 CardView 사용하는 방법과 동일하게 사용하시면 됩니다.
간단한 샘플을 올려뒀습니다.

```xml
<soup.neumorphism.NeumorphCardView>
    <androidx.constraintlayout.widget.ConstraintLayout>
        <ImageView />
        <TextView />
        <TextView />
        <soup.neumorphism.NeumorphButton />
    </androidx.constraintlayout.widget.ConstraintLayout>
</soup.neumorphism.NeumorphCardView>
```

<img width="300" src="https://user-images.githubusercontent.com/3405740/83755260-3f017c80-a6a8-11ea-80c1-126a9a252c60.png" />

**Comment by Rabbitg** [comment]
정말 감사합니다ㅠㅠ 실은 4학년이라 과제로 어플 만드는 중인데 뉴모피즘 디자인을 찾던 중 fornewid님 라이브러리를 사용하고 있었습니다. !! 질문을 먼저 할 걸 그랬나봐요 ㅠㅠ 어떻게서든 안됐었는데.. 감사합니다 !! 좋은밤 되세요 ^^

**Comment by fornewid** [comment]
얼마든지 물어보셔도 되죠 ㅎㅎ
그럼 졸업 작품 잘 만드세요! 화이팅

**Comment by fornewid** [comment]
졸업작품 만드시다가 더 필요하다거나, 뭔가 이상한 점이 있다면 이슈로 많이많이 올려주세요~ :)
