### ISSUE TITLE
저 혹시 버튼에 색상을 입히려고 하는데 어떻게 할 수 있는건가요??

### ISSUE THREAD

**Issue by Rabbitg** [fornewid/neumorphism#21]
background = "#212121"
이런식으로 입혀볼까하는데 적용이 되질 않네요 ..
혹시 방법 아신다면 공유 부탁드립니다 ^^ !!

**Comment by Rabbitg** [comment]
> background = "#212121"
> 이런식으로 입혀볼까하는데 적용이 되질 않네요 ..
> 혹시 방법 아신다면 공유 부탁드립니다 ^^ !!
엇 찾았습니다 죄송합니다 !!

**Comment by fornewid** [comment]
아래처럼 사용하시면 됩니다. 해결된 내용이면 이슈를 닫아주세요. ㅎㅎ
```xml
    // Set background or stroke
    app:neumorph_backgroundColor="@color/background_color"
    app:neumorph_strokeColor="@color/stroke_color"
    app:neumorph_strokeWidth="@dimen/stroke_width"
```
