### ISSUE TITLE
option to disable dark them

### ISSUE THREAD

**Issue by MirzaAhmedBaig** [fornewid/neumorphism#24]
Thanks for such a great library, i am working on app that does not need to support dark mood. There is no such option in this library

**Comment by fornewid** [comment]
@MirzaAhmedBaig
Are you using the `Theme.Neumorph.DayNight.*` theme?
`DayNight` means that it supports Light / Dark.
If you want to fix it in Light mode without Dark mode, please use `Light` theme.

If it's not the problem I mentioned, can you show me the code?
