### ISSUE TITLE
Error in import library

### ISSUE THREAD

**Issue by winigma** [fornewid/neumorphism#28]
Version used:

Error in iport library in my project
version: 0.1.11.

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.github.fornewid:neumorphism:0.1.11
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.fornewid:neumorphism:0.1.11
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.github.fornewid:neumorphism:0.1.11

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.github.fornewid:neumorphism:0.1.11.
Show Details
Affected Modules: app

I would like to use a library, but I am using this error when importing, makes many updates to the tools and android studio, nothing seems to solve

**Comment by fornewid** [comment]
Please check a comment in #17 issue.
If not the reason, reopen this with more details. :)

**Comment by singhbabu9455** [comment]
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.fornewid:neumorphism:{latest_version}.

**Comment by singhbabu9455** [comment]
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.fornewid:neumorphism:{latest_version}.
   facing this problem
