### ISSUE TITLE
Problem with tablets

### ISSUE THREAD

**Issue by omis76** [fornewid/neumorphism#31]
Version used: 0.1.11
Devices/Android versions reproduced on: Lenovo Tab/ Some Custom made tables (Version: 8.1.0)
![screenshot-1596001983448](https://user-images.githubusercontent.com/20901821/88761998-e6bd9700-d18d-11ea-9972-c37eb396c517.jpg)

- A screenshots showing the issue. As you can see its showing border for both white and grey shadow in tablet, but ran the same code in pixel 3a its working like a charm

**Comment by fornewid** [comment]
Thanks for report! I'm really sorry for the late response.
I found some issues with low dpi. (mdpi, ldpi)
I'll fix it quickly. 🔧

**Comment by fornewid** [comment]
This bug is fixed in `0.2.0` version.
Please check this issue is also fixed on your usecases.
If not, please tell me.
