### ISSUE TITLE
Flat and pressed state

### ISSUE THREAD

**Issue by Dorokhovyegor** [fornewid/neumorphism#4]
Do you want to add flat && pressed state at the same time? it should be great, bacause it can help to add these effects (there are internal and external shadows at the same time)

![image](https://user-images.githubusercontent.com/37757367/79848510-d85f2280-83c9-11ea-8417-22189bdf37a5.png)

**Comment by Dorokhovyegor** [comment]
Chtobi zavtra bilo

**Comment by fornewid** [comment]
> there are internal and external shadows at the same time

I missed that! 😮
Thank you for proposal.
I'll consider this ASAP.

**Comment by fornewid** [comment]
I added new ShapeType on 0.1.2 version. (BASIN)
Well... maybe it's not a good word. 🤔 
If you think a better word, please comment to me. :)

Anyway, use the following code to apply new ShapeType.
```xml
<soup.neumorphism.NeumorphismCardView
    ...
    app:neumorph_shapeType="basin" />
```
