### ISSUE TITLE
How to use Textview i have tried your methode but no result 

### ISSUE THREAD

**Issue by DkKhan786** [fornewid/neumorphism#46]
Here is textview code i am using can you please correct it if there is any problem in code

```
<soup.neumorphism.NeumorphTextView
        style="@style/Widget.Neumorph.TextView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World"
        android:textSize="30sp" />
```

**and result it here** 

![image](https://user-images.githubusercontent.com/41612646/94339250-da30b000-0011-11eb-9fe4-36408bf04fb3.png)

**Comment by leonlee0116** [comment]
`<soup.neumorphism.NeumorphTextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:neumorph_shadowColorLight="?colorPrimary"
            app:neumorph_shadowColorDark="?colorPrimaryDark"
            android:textColor="?android:colorBackground"
            android:text="Sunday"
            android:textStyle="bold"
            android:textSize="60sp" />`

Try this

**Comment by fornewid** [comment]
@DkKhan786 
Are there any sample projects I can test out?
And please tell me a more detailed test environment. 😄

**Comment by DkKhan786** [comment]
No thank you bro love it ❤️

**Comment by DkKhan786** [comment]
@fornewid i have made detail tutorial on this library ❤️

[](https://www.youtube.com/channel/UCr-2CwkKhO6fQf58vBv5WoQ)

**Comment by fornewid** [comment]
Wow! 😮
It's so cool! 🎉 🎉 🎉

**Comment by fornewid** [comment]
The issue has been resolved.
