### ISSUE TITLE
Button pressed and release animation that shown in the picture?

### ISSUE THREAD

**Issue by leonlee0116** [fornewid/neumorphism#47]
Hi anyone, first thanks to the author for this library!
My question is as the title, I'm not sure how to achieve that effect and press and release a button
In the the picture that author attached has some kind of fade in and out on the light shadow

**Comment by gregoire-mrd** [comment]
Hello, if i'm thinking right. 
You must put `<item name="android:stateListAnimator">@animator/button_neumorph_animator</item>` in the style of the neumorph element. You can find the code of this animation in the sample app.

**Comment by leonlee0116** [comment]
thank you so much! forgot to put the style tag

**Comment by fornewid** [comment]
In `0.2.2` version, apply press animation for all widgets. 😄
