### ISSUE TITLE
NeumorphTextView setText Problem

### ISSUE THREAD

**Issue by leonlee0116** [fornewid/neumorphism#49]
Hi, is it normal that setText on NeumorphTextView during runtime, the shadow will not be redraw?
I'm not sure is it I'm doing it wrong or not. 

<soup.neumorphism.NeumorphTextView
        android:id="@+id/tv_time"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:neumorph_shadowColorLight="?colorPrimary"
        app:neumorph_shadowColorDark="?colorPrimaryDark"
        app:neumorph_backgroundColor="?android:colorBackground"
        android:textColor="?android:colorBackground"
        android:text="10\n30"
        app:layout_constraintTop_toTopOf="@id/some_view1"
        app:layout_constraintBottom_toTopOf="@id/some_view2"
        app:layout_constraintVertical_bias="0.25"
        android:textSize="80sp"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintEnd_toEndOf="parent"/>

**Comment by fornewid** [comment]
Fixed in `0.2.2`.

**Comment by leonlee0116** [comment]
thank you so much for your hardwork!

**Comment by protoss5482** [comment]
Same error

`implementation 'com.github.fornewid:neumorphism:0.3.0'`

![image](https://user-images.githubusercontent.com/5569022/107689346-62f27480-6cb1-11eb-9c74-766d258bdda5.png)

**Comment by Tiarait** [comment]
> Same error
> 
> `implementation 'com.github.fornewid:neumorphism:0.3.0'`
> 

I have the same problem in v0.3.2, when use digital characters  in setText. (ip address)
For this I used the following 
` neumorphTextView?.text = "0.0.0.0"
  handler.post {
      neumorphTextView?.text = newIP
  }`

Unfortunately `invalidate()` , `requestLayout()`, `visibility = View.GONE` - not helping
