### ISSUE TITLE
Allow to change corner radius for all 3 types of shape

### ISSUE THREAD

**Issue by felislynx-silae** [fornewid/neumorphism#5]
Just like in title, i would like to be able to change corner radius on every type of shape :). I think your library is closest to being best one on Android. It misses some configuration additions. Maybe onTouch effects for buttons might be also a good idea (i didn't find on click effect while trying your lib out).

**Comment by fornewid** [comment]
Thanks for the feedback.
First, the corner radius of the shape can still be changed.
But there is no example code or guide.
So I will update soon.

Secondly, I'm wondering which click effect will be good. 🤔 
Please suggest any suitable options.
(I think, ripple effect are not so good.)

**Comment by felislynx-silae** [comment]
When i was making neumorphic effect (much, much simpler, withou rs, just on shadow paint and paths), i made ~600ms animation from raised one to pushed down where outer shadow goes to 0 which gives flat surface and then inner shadow is shown to pushed down effect. I treated those two as two states. Bazel one for me is rather container within i can put raised buttons. Something like slider with button inside :).

**Comment by fornewid** [comment]
The function to customize corner size is added in 0.1.3
Please check the following codes.

```xml
​<​soup​.neumorphism.NeumorphCardView
    ...
    ​app​:​neumorph_shapeAppearance​=​"​@style/CustomShapeAppearance​"​ />

<​style​ ​name​=​"​CustomShapeAppearance​"​>
    <​item​ ​name​=​"​neumorph_cornerFamily​"​>{rounded|oval}</​item​>
    <​item​ ​name​=​"​neumorph_cornerSize​"​>32dp</​item​>
</​style​>
```

**Comment by felislynx-silae** [comment]
I'll take a look as soon as possible and will let you know how it went :)

**Comment by felislynx-silae** [comment]
It is better, but basin is misbehaving.
This is a result
![device-2020-04-28-132035](https://user-images.githubusercontent.com/1098831/80481784-6d769400-8953-11ea-8432-8cad167e31b5.png)
But i would like to achieve something like this:
<img width="214" alt="Zrzut ekranu 2020-04-28 o 13 20 53" src="https://user-images.githubusercontent.com/1098831/80481823-7b2c1980-8953-11ea-92f5-64fd82ae291a.png">

**Comment by fornewid** [comment]
So sorry for slow response. 😭 
You're right.
I think.. a corner radius is over half width of view.
then it occurs on PressedShape.
I'll fix soon.

**Comment by fornewid** [comment]
In 0.1.5 version, this issue is fixed.
