### ISSUE TITLE
CardView Issue

### ISSUE THREAD

**Issue by anilUpadhyay01** [fornewid/neumorphism#50]
I would appreciate if you could resolve:
- When i used neumorphism cardView in RecyclerView after recyclerView scrolling is not smooth as before its working smoothly please verify this and give me a solution

**Comment by IBit-Company** [comment]
same problem here

**Comment by akhvi** [comment]
some problem.. sometime crash especially in big list in recycleview.. for this problem i change cardView to neumorpImageView as a background, still beautiful and more smoot and not crash

**Comment by fornewid** [comment]
Fixed in `0.3.0`.
