### ISSUE TITLE
안녕하세요! 버튼 관련해서 질문드립니다.

### ISSUE THREAD

**Issue by parkwoongki** [fornewid/neumorphism#6]
안녕하세요. 
혹시 향후에 버튼에 버튼 터치 시 pressed효과를 넣으실 계획이 있으신가요?
좋은 하루 되세요!

**Comment by fornewid** [comment]
말씀하신 pressed 효과는 구체적으로 어떤 것을 생각하시나요?
effect는 생각하고 있지만, 아직 구체적인 안을 정하지는 않았습니다.
괜찮은 옵션이 있다면 제안 부탁드립니다. :)

**Comment by parkwoongki** [comment]
아 제 질문이 조금 난해했던 것 같습니다! 말씀하신 effect가 맞습니다. 제가 버튼을 터치하면 터치된 모습(pressed 된 모습)이 되길 원하는데 제가 아직 많이 부족해서 코드상으로 button.setShapeType(1)를 사용해서 눌린 모양을 만드는데 어려움이 있었습니다. 

그래서 향후에 button에 터치 시에 눌린 effect를 적용하실 계획이 있으신지 말씀 드린겁니다! 제 생각은 버튼에
평상시 : flat
터치된 상태 : pressed
이렇게만 된다면 좋을 것 같습니다!
감사합니다.

**Comment by RainkQ** [comment]
```
class NeumorphismOnTouchListener implements View.OnTouchListener {
        @Override
        public boolean onTouch(View v, MotionEvent event) {
            if (v instanceof NeumorphButton) {
                NeumorphButton b = (NeumorphButton) v;
                if(event.getAction() == MotionEvent.ACTION_UP){
                    b.performClick();
                    b.setShapeType(ShapeType.FLAT);
                }
                if(event.getAction() == MotionEvent.ACTION_DOWN){
                    b.setShapeType(ShapeType.PRESSED);
                }
            }
            return false;
        }
    }
```
Have you tried overwrite `setOnTouchListener' to be something like this?
I'm new to android dev, just a suggestion.

**Comment by fornewid** [comment]
0.1.4 버전에서 아래 컴포넌트에 눌림효과를 지원합니다.
- `NeumorphButton`
- `NeumorphFloatingActionButton`
- `NeumorphImageButton`
----
In 0.1.4 version, supports press effect for the following components:
- `NeumorphButton`
- `NeumorphFloatingActionButton`
- `NeumorphImageButton`
