### ISSUE TITLE
neumorphic TextView style does not work when text is set/changed by java class

### ISSUE THREAD

**Issue by rockakassh** [fornewid/neumorphism#61]
Version used: 0.2.1
Devices/Android versions reproduced on: Android 10

 When i try to set different text from java class, only previously set text(in xml) shadow & elevation shows in layout with new text.
for examaple,
suppose, in xml, "Hello World" text has been set in a soup.neumorphism.NeumorphTextView -> at this stage everything looks good.
then when i change this text to a new one from java class, suppose "Hello There!" -> shadow and elevation style remains the same of  "Hello World" but text changes to new one "Hello There!". This means neumorphic effect of text "Hello World" remains there even if i changed the text and new neumorphic effect of text "Hello There!" does not drawn. it looks like visible text is different from neumorphic text in background.

There are number of issues in soup.neumorphism.NeumorphTextView:
1. explained above
2. Inherited from above issue: if text is multiline, then whole neumorphic effect is drawn in single line even if text is wrapped in new lines if there is no space left in first line.
3. neumorphic effect of ellipses does not draw when ellipses  enabled whether it is at the end or start if text is more than available space. it looks very ugly because instead of ellipses, it draws usual text in place of ellipses.
4. When width is set to match parant in  soup.neumorphism.NeumorphTextView, and text alignment is set to  center,   text is drawn at center as expected but neumorphic effect of that text is drawn at start that make it impossible to use in some cases when alignment is needed.
5. when padding is set in soup.neumorphism.NeumorphTextView, neumorphic effect of text is draw at start as in case 4.

All the above issues makes it ugly when text is more than available screen space, if text is not set in xml then it does not draw neumorphic effect even if text is set from java class.

**Comment by fornewid** [comment]
> When i try to set different text from java class, only previously set text(in xml) shadow & elevation shows in layout with new text.
for examaple,
suppose, in xml, "Hello World" text has been set in a soup.neumorphism.NeumorphTextView -> at this stage everything looks good.
then when i change this text to a new one from java class, suppose "Hello There!" -> shadow and elevation style remains the same of "Hello World" but text changes to new one "Hello There!". This means neumorphic effect of text "Hello World" remains there even if i changed the text and new neumorphic effect of text "Hello There!" does not drawn. it looks like visible text is different from neumorphic text in background.

Please test this again on `0.3.0`. 😄

**Comment by rockakassh** [comment]
Gravity and padding issues are still there.
