### ISSUE TITLE
The dependency does  not work, android responded with an eror

### ISSUE THREAD

**Issue by michaelMdMlavia** [fornewid/neumorphism#69]
Version used: 4.0.1

![Screenshot (393)](https://user-images.githubusercontent.com/77862705/106401883-5ce9d180-642f-11eb-9b20-6f241431fc2d.png)
.

**Comment by MrRoot313** [comment]
@michaelMdMlavia Please try with implementation 'com.github.fornewid:neumorphism:0.3.0'
