### ISSUE TITLE
New to programming, trying to get neumorphism working in android studio.

### ISSUE THREAD

**Issue by HenriHawk42** [fornewid/neumorphism#72]
Hey there, I'm new to android studio and programming in general, and I decided to make a basic app. I decided I wanted to make the UI neumorphic, so I found this library. I got the dependencies in Gradle without a hitch, but I have no clue how to start the UI. Do I put something in a fragment XML file? do I replace something? I tried putting the example in an XML fragment file, but I got an error message "Cannnot resolve class soup.neumorphism.NeumorphCardView". How do I start making the UI, and can I edit in the visual editor, or can I only use XML? Sorry for the trouble lol

**Comment by fornewid** [comment]
I can't reproduce this issue.
If you can reproduce it, please share your sample project.
