### ISSUE TITLE
TextView on top on CardView doesnt allow touch on cardview

### ISSUE THREAD

**Issue by Surakshaajith** [fornewid/neumorphism#74]
Version used:
Devices/Android versions reproduced on: 10

I have a Textview on top of NeumorphCardView. When i press on textview the card is not clickable.
I tried disabling the textview but it doesnt work.

```
android:clickable="false"
android:focusable="false"
android:focusableInTouchMode="false"
```

PS: I am using this card in recycler view

**Comment by fornewid** [comment]
I can't reproduce this issue.
If you can reproduce it, please share your sample project.

**Comment by GauravCreed** [comment]
Hi @fornewid and @Surakshaajith 

same issue I face in my app also, have u found the solution for this?

Thanks(_)
