### ISSUE TITLE
Translation and reprinting authorization

### ISSUE THREAD

**Issue by Alreys** [fornewid/neumorphism#75]
Hello author, can I translate and reprint your article on the CSDN(https://www.csdn.net/) technology website in China, including the RADEME.md file in github, to help expand the influence and usage rate of your plugin.

**Comment by fornewid** [comment]
Yes, you can use it freely.

**Comment by Alreys** [comment]
Article URL  https://blog.csdn.net/qq_17282141/article/details/113945103
