### ISSUE TITLE
Cannot resolve symbol 'NeumorphCardView

### ISSUE THREAD

**Issue by mnawaf** [fornewid/neumorphism#78]
Hi,
I added in implementation as follows:
    implementation 'com.github.fornewid:neumorphism:0.3.0'
I added in allprojects as follows:
allprojects {
    repositories {
        maven { url "https://jitpack.io" }
        jcenter()
        google()

    }
}
I've been using it for more than a month everything is ok,
now I started seeing this error (Cannot resolve symbol 'NeumorphCardView)
I tried it in a new empty android project all the same.
what am I doing wrong?
![Untitled-2](https://user-images.githubusercontent.com/30872147/112714748-ec21db80-8eec-11eb-8109-623e752462d4.jpg)

**Comment by fornewid** [comment]
I can't reproduce this issue.
If you can reproduce it, please share your sample project.
