### ISSUE TITLE
How to change color of button

### ISSUE THREAD

**Issue by MirzaAhmedBaig** [fornewid/neumorphism#8]
I am trying to color of button with this but it is not working

```
<soup.neumorphism.NeumorphButton
        android:id="@+id/button"
        style="@style/Widget.Neumorph.Button"
        android:layout_width="0dp"
        android:layout_height="60dp"
        android:layout_marginBottom="100dp"
        android:text="Start Meditation"
        android:background="#ff000"
        app:layout_constraintBottom_toTopOf="@+id/button2"
        app:layout_constraintEnd_toEndOf="@+id/button2"
        app:layout_constraintStart_toStartOf="@+id/button2"
        app:neumorph_shadowColorDark="#CCD1D9E6"
        app:neumorph_shadowColorLight="#CCFFFFFF"
        app:neumorph_shapeType="flat" />
```

**Comment by fornewid** [comment]
Um.. the upper codes are working on me. 😅 
Can you explain more details, please? (OS version or device etc..)

The following is screenshot on my device.

<img width="400" src="https://user-images.githubusercontent.com/3405740/81318513-55c4ab80-90c9-11ea-9f9f-90a138270d8b.png" />

**Comment by MirzaAhmedBaig** [comment]
hey i have given button background red color as you can see
android:background="#ff000"
then how it is working in screenshot?

**Comment by fornewid** [comment]
OK, I understood.
I misunderstood it as a question on how to change the shadow color.
Changing the background is important things. It's a bug, right.
I'll fix it, soon.

**Comment by fornewid** [comment]
In 0.1.5 version, `backgroundColor` attribute is added.

<img width="500" src="https://user-images.githubusercontent.com/3405740/81422593-20ce5c80-918e-11ea-86ef-a6a27c4d1e2c.png" />

```xml
<soup.neumorphism.NeumorphButton
    ...
    android:text="Button"
    app:neumorph_backgroundColor="#ff0000"
    app:neumorph_strokeColor="#00ff00"
    app:neumorph_strokeWidth="2dp" />
```
