### ISSUE TITLE
Unresolved reference: databinding, now i try to run sample...

### ISSUE THREAD

**Issue by Vincent170608** [fornewid/neumorphism#85]
i am using android studio 3.5.2.
i try to test the giving sample, but it can not resolved reference: databinding, such as
![databinding](https://user-images.githubusercontent.com/91554909/135123620-386ced55-b5bc-491e-9b0a-1964215bf665.png)
i want to konw what's wrong in my project.

**Comment by MasaYanagida** [comment]
Hi. Have you added viewBinding option to build.gradle?
```
android {
  viewBinding {
    enabled = true
  }
}
```

**Comment by McYeets** [comment]
I am experiencing the same error even though I have added this line in my build.gradle:
    buildFeatures{
        dataBinding = true
        viewBinding = true
    }

![Image](https://github.com/user-attachments/assets/60d743ca-58fe-42ed-8ed4-6aaae22e2dbe)
