### ISSUE TITLE
Task failed with an exception.

### ISSUE THREAD

**Issue by anubhav-hl** [fornewid/neumorphism#89]
Version used: 0.3.0
Execution failed for task ':app:desugarDebugFileDependencies'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.fornewid:neumorphism:0.3.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/fornewid/neumorphism/0.3.0/neumorphism-0.3.0.pom
       - https://repo.maven.apache.org/maven2/com/github/fornewid/neumorphism/0.3.0/neumorphism-0.3.0.pom
       - https://jcenter.bintray.com/com/github/fornewid/neumorphism/0.3.0/neumorphism-0.3.0.pom
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Please fix this.

**Comment by fornewid** [comment]
I can't reproduce this issue.
If you can reproduce it, please share your sample project.
