### ISSUE TITLE
Update for Android 12

### ISSUE THREAD

**Issue by astankov** [fornewid/neumorphism#91]
Android 12 is already here.
So by updating android and should be updated 
kotlin-stdlib-jdk7:1.4.10 to 
kotlin-stdlib-jdk7:1.6.0
Is there any plan for update soon?

**Comment by surendar2831** [comment]
It is not supporting Android 12.

**Comment by fornewid** [comment]
I can't reproduce this issue.
If you can reproduce it, please share your sample project.
